### Packages

In [46]:
import numpy as np
import torch
import torchvision
from PIL import Image
from torch import nn
from torch.nn import functional as F
from torch.utils import data
from torchvision import transforms

#################   WARNING   ################
# The below part is generated automatically through:
#    d2lbook build lib
# Don't edit it directly

import collections
import hashlib
import inspect
import math
import os
import random
import re
import shutil
import sys
import tarfile
import time
import zipfile
from collections import defaultdict
import pandas as pd
import requests
from IPython import display
from matplotlib import pyplot as plt
from matplotlib_inline import backend_inline

import numpy as np
import torch
import torchvision
from PIL import Image
from scipy.spatial import distance_matrix
from torch import nn
from torch.nn import functional as F
from torchvision import transforms

In [47]:
d2l = sys.modules[__name__]
nn_Module = nn.Module
d2l, nn_Module

(<module '__main__'>, torch.nn.modules.module.Module)

# Prerequisites

本节主要包含pytorch框架下的张量基本操作。

### Hello, torch

In [48]:
x = torch.arange(12)  # 默认创建为整数
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [49]:
x.shape  # shape属性访问张量形状

torch.Size([12])

In [50]:
x.numel()  # 张量元素个数

12

把张量x从形状为（12,）的行向量转换为形状为（3,4）的矩阵：

In [51]:
x_reshape = x.reshape(3, 4)
x_reshape

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

reshape属性里的-1：

In [52]:
print(x.reshape(-1, 4))  # 我们可以通过-1来调用此自动计算出维度的功能。 即我们可以用x.reshape(-1,4)或x.reshape(3,-1)来取代x.reshape(3,4).
print(x.reshape(3, -1))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


zeros(), ones()函数：

In [53]:
print(torch.zeros((2, 3, 4)))
torch.ones(2, 3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [54]:
torch.randn(3, 4)  # 创建一个形状为（3,4）的张量。 其中的每个元素都从均值为0、标准差为1的标准高斯分布（正态分布）中随机采样

tensor([[ 0.6706, -0.6188,  1.4091,  0.1759],
        [-0.4409, -1.1803,  1.5087, -0.4949],
        [-0.6346, -0.1790, -1.0997, -0.0523]])

tensor加减乘除：

In [55]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [56]:
torch.exp(x)  # 求幂运算

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

张量连结（concatenate）：

In [57]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2., 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)  # 一行行拼接在一起(dim = 0), 一列列拼接在一起(dim = 1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

数据类型：

In [58]:
y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(y.dtype)
y = torch.tensor([[2., 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])  # 2变成了2.
print(y.dtype)

torch.int64
torch.float32


In [59]:
X == Y  # 逻辑运算

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [60]:
X.sum()  # 求和

tensor(66.)

### Broadcasting Mechanism

In [61]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b  # 沿着数组中长度为1的轴进行广播

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [62]:
a + b  # 广播为一个更大的3 * 2矩阵，如下所示：矩阵a将复制列， 矩阵b将复制行，然后再按元素相加

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### Indices and Slices

In [63]:
X[-1], X[1:3]  # 可以用[-1]选择最后一个元素，可以用[1:3]选择第二个和第三个元素

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [64]:
X[1, 2] = 9
X  # 将元素写入矩阵

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])